version: '3.5'
services:
  api:
    image: api
    hostname: api
    depends_on:
      - db

  db:
    image: postgres
    hostname: postgres
    command: ['postgres', '-c', 'max_connections=500']
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
